{
 "openapi": "3.1.0",
 "info": {
  "title": "Google Sheets API",
  "version": "v4",
  "description": "Reads and writes Google Sheets."
 },
 "servers": [
  {
   "url": "https://sheets.googleapis.com/"
  }
 ],
 "paths": {
  "/v4/spreadsheets": {
   "post": {
    "operationId": "sheets.spreadsheets.create",
    "x-executor-toolPath": "sheets.spreadsheets.create",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}": {
   "get": {
    "operationId": "sheets.spreadsheets.get",
    "x-executor-toolPath": "sheets.spreadsheets.get",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. By default, data within grids is not returned. You can include grid data in one of 2 ways: * Specify a [field mask](https://developers.google.com/workspace/sheets/api/guides/field-masks) listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData URL parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreadsheets,[...]",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}": {
   "get": {
    "operationId": "sheets.spreadsheets.developerMetadata.get",
    "x-executor-toolPath": "sheets.spreadsheets.developerMetadata.get",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata).",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/developerMetadata:search": {
   "post": {
    "operationId": "sheets.spreadsheets.developerMetadata.search",
    "x-executor-toolPath": "sheets.spreadsheets.developerMetadata.search",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns all developer metadata matching the specified DataFilter. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting that region.[...]",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo": {
   "post": {
    "operationId": "sheets.spreadsheets.sheets.copyTo",
    "x-executor-toolPath": "sheets.spreadsheets.sheets.copyTo",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values/{range}": {
   "get": {
    "operationId": "sheets.spreadsheets.values.get",
    "x-executor-toolPath": "sheets.spreadsheets.values.get",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns a range of values from a spreadsheet. The caller must specify the spreadsheet ID and a range.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   },
   "put": {
    "operationId": "sheets.spreadsheets.values.update",
    "x-executor-toolPath": "sheets.spreadsheets.values.update",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID, range, and a valueInputOption.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values/{range}:append": {
   "post": {
    "operationId": "sheets.spreadsheets.values.append",
    "x-executor-toolPath": "sheets.spreadsheets.values.append",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Appends values to a spreadsheet. The input range is used to search for existing data and find a \"table\" within that range. Values will be appended to the next row of the table, starting with the first column of the table. See the [guide](https://developers.google.com/workspace/sheets/api/guides/values#appending_values) and [sample code](https://developers.google.com/workspace/sheets/api/samples/writing#append_values) for specific details of how tables are detected and data [...]",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values/{range}:clear": {
   "post": {
    "operationId": "sheets.spreadsheets.values.clear",
    "x-executor-toolPath": "sheets.spreadsheets.values.clear",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Clears values from a spreadsheet. The caller must specify the spreadsheet ID and range. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchClear": {
   "post": {
    "operationId": "sheets.spreadsheets.values.batchClear",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchClear",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges. Only values are cleared -- all other properties of the cell (such as formatting and data validation) are kept.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter": {
   "post": {
    "operationId": "sheets.spreadsheets.values.batchClearByDataFilter",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchClearByDataFilter",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Clears one or more ranges of values from a spreadsheet. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching any of the specified data filters will be cleared. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc.) are kept.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchGet": {
   "get": {
    "operationId": "sheets.spreadsheets.values.batchGet",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchGet",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter": {
   "post": {
    "operationId": "sheets.spreadsheets.values.batchGetByDataFilter",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchGetByDataFilter",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns one or more ranges of values that match the specified data filters. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID and one or more DataFilters. Ranges that match any of the data filters in the request will be returned.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchUpdate": {
   "post": {
    "operationId": "sheets.spreadsheets.values.batchUpdate",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchUpdate",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more ValueRanges.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter": {
   "post": {
    "operationId": "sheets.spreadsheets.values.batchUpdateByDataFilter",
    "x-executor-toolPath": "sheets.spreadsheets.values.batchUpdateByDataFilter",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Sets values in one or more ranges of a spreadsheet. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID, a valueInputOption, and one or more DataFilterValueRanges.",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}:batchUpdate": {
   "post": {
    "operationId": "sheets.spreadsheets.batchUpdate",
    "x-executor-toolPath": "sheets.spreadsheets.batchUpdate",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Applies one or more updates to the spreadsheet. Each request is validated before being applied. If any request is not valid then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. The replies will mirror the requests. For example, if you applied 4 updates and the 3rd one had a reply, then the response will have 2 empty replies, the actual reply, and another empty reply, in that order. D[...]",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  },
  "/v4/spreadsheets/{spreadsheetId}:getByDataFilter": {
   "post": {
    "operationId": "sheets.spreadsheets.getByDataFilter",
    "x-executor-toolPath": "sheets.spreadsheets.getByDataFilter",
    "tags": [
     "Google Sheets API"
    ],
    "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). This method differs from GetSpreadsheet in that it allows selecting which subsets of spreadsheet data to return by specifying a dataFilters parameter. Multiple DataFilters can be specified. Specifying one or more data filters returns the portions of the spreadsheet[...]",
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/spreadsheets"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/drive.file"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/spreadsheets",
     "https://www.googleapis.com/auth/drive.file"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "googleOAuth2": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
       "openid": "",
       "email": "",
       "profile": "",
       "https://www.googleapis.com/auth/spreadsheets": "",
       "https://www.googleapis.com/auth/drive.file": ""
      }
     }
    }
   }
  }
 },
 "security": [
  {
   "googleOAuth2": [
    "openid",
    "email",
    "profile",
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.file"
   ]
  }
 ],
 "x-executor-origin": {
  "kind": "googleDiscoveryBundle",
  "services": [
   {
    "discoveryUrl": "https://www.googleapis.com/discovery/v1/apis/sheets/v4/rest",
    "service": "sheets",
    "version": "v4"
   }
  ]
 }
}