{
 "openapi": "3.1.0",
 "info": {
  "title": "Gmail API",
  "version": "v1",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels."
 },
 "servers": [
  {
   "url": "https://www.googleapis.com/"
  }
 ],
 "paths": {
  "/gmail/v1/users/{userId}/watch": {
   "post": {
    "operationId": "gmail.users.watch",
    "x-executor-toolPath": "gmail.users.watch",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/watch",
    "tags": [
     "Gmail API"
    ],
    "description": "Set up or update a push notification watch on the given user mailbox. For more information, see [Configure push notifications in Gmail API](https://developers.google.com/workspace/gmail/api/guides/push).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/stop": {
   "post": {
    "operationId": "gmail.users.stop",
    "x-executor-toolPath": "gmail.users.stop",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/stop",
    "tags": [
     "Gmail API"
    ],
    "description": "Turn off push notification delivery for the given user mailbox. For more information, see [Configure push notifications in Gmail API](https://developers.google.com/workspace/gmail/api/guides/push).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/profile": {
   "get": {
    "operationId": "gmail.users.getProfile",
    "x-executor-toolPath": "gmail.users.getProfile",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/profile",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the current user's Gmail profile.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/history": {
   "get": {
    "operationId": "gmail.users.history.list",
    "x-executor-toolPath": "gmail.users.history.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/history",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`). For more information, see [Synchronize clients with Gmail](https://developers.google.com/workspace/gmail/api/guides/sync).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/imap": {
   "get": {
    "operationId": "gmail.users.settings.getImap",
    "x-executor-toolPath": "gmail.users.settings.getImap",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/imap",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets IMAP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "put": {
    "operationId": "gmail.users.settings.updateImap",
    "x-executor-toolPath": "gmail.users.settings.updateImap",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/imap",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates IMAP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/language": {
   "get": {
    "operationId": "gmail.users.settings.getLanguage",
    "x-executor-toolPath": "gmail.users.settings.getLanguage",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/language",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets language settings. For more information, see [Manage language settings](https://developers.google.com/workspace/gmail/api/guides/language-settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "put": {
    "operationId": "gmail.users.settings.updateLanguage",
    "x-executor-toolPath": "gmail.users.settings.updateLanguage",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/language",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates language settings. For more information, see [Manage language settings](https://developers.google.com/workspace/gmail/api/guides/language-settings). If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead."[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/vacation": {
   "put": {
    "operationId": "gmail.users.settings.updateVacation",
    "x-executor-toolPath": "gmail.users.settings.updateVacation",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/vacation",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates vacation responder settings. For more information, see [Manage vacation settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/vacation_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "get": {
    "operationId": "gmail.users.settings.getVacation",
    "x-executor-toolPath": "gmail.users.settings.getVacation",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/vacation",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets vacation responder settings. For more information, see [Manage vacation settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/vacation_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/pop": {
   "put": {
    "operationId": "gmail.users.settings.updatePop",
    "x-executor-toolPath": "gmail.users.settings.updatePop",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/pop",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates POP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "get": {
    "operationId": "gmail.users.settings.getPop",
    "x-executor-toolPath": "gmail.users.settings.getPop",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/pop",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets POP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/autoForwarding": {
   "get": {
    "operationId": "gmail.users.settings.getAutoForwarding",
    "x-executor-toolPath": "gmail.users.settings.getAutoForwarding",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/autoForwarding",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the auto-forwarding setting for the specified account. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/forwardingAddresses": {
   "get": {
    "operationId": "gmail.users.settings.forwardingAddresses.list",
    "x-executor-toolPath": "gmail.users.settings.forwardingAddresses.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/forwardingAddresses",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the forwarding addresses for the specified account. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}": {
   "get": {
    "operationId": "gmail.users.settings.forwardingAddresses.get",
    "x-executor-toolPath": "gmail.users.settings.forwardingAddresses.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified forwarding address. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}": {
   "get": {
    "operationId": "gmail.users.settings.sendAs.get",
    "x-executor-toolPath": "gmail.users.settings.sendAs.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "patch": {
    "operationId": "gmail.users.settings.sendAs.patch",
    "x-executor-toolPath": "gmail.users.settings.sendAs.patch",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
    "tags": [
     "Gmail API"
    ],
    "description": "Patch the specified send-as alias. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "put": {
    "operationId": "gmail.users.settings.sendAs.update",
    "x-executor-toolPath": "gmail.users.settings.sendAs.update",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings). Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/sendAs": {
   "get": {
    "operationId": "gmail.users.settings.sendAs.list",
    "x-executor-toolPath": "gmail.users.settings.sendAs.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault": {
   "post": {
    "operationId": "gmail.users.settings.sendAs.smimeInfo.setDefault",
    "x-executor-toolPath": "gmail.users.settings.sendAs.smimeInfo.setDefault",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
    "tags": [
     "Gmail API"
    ],
    "description": "Sets the default S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}": {
   "get": {
    "operationId": "gmail.users.settings.sendAs.smimeInfo.get",
    "x-executor-toolPath": "gmail.users.settings.sendAs.smimeInfo.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "delete": {
    "operationId": "gmail.users.settings.sendAs.smimeInfo.delete",
    "x-executor-toolPath": "gmail.users.settings.sendAs.smimeInfo.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Deletes the specified S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo": {
   "get": {
    "operationId": "gmail.users.settings.sendAs.smimeInfo.list",
    "x-executor-toolPath": "gmail.users.settings.sendAs.smimeInfo.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists S/MIME configs for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "post": {
    "operationId": "gmail.users.settings.sendAs.smimeInfo.insert",
    "x-executor-toolPath": "gmail.users.settings.sendAs.smimeInfo.insert",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
    "tags": [
     "Gmail API"
    ],
    "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that `pkcs12` format is required for the key. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}": {
   "get": {
    "operationId": "gmail.users.settings.cse.keypairs.get",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
    "tags": [
     "Gmail API"
    ],
    "description": "Retrieves an existing client-side encryption key pair. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gmail.settings.[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/keypairs": {
   "post": {
    "operationId": "gmail.users.settings.cse.keypairs.create",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.create",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority)[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "get": {
    "operationId": "gmail.users.settings.cse.keypairs.list",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists client-side encryption key pairs for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gmai[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable": {
   "post": {
    "operationId": "gmail.users.settings.cse.keypairs.enable",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.enable",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
    "tags": [
     "Gmail API"
    ],
    "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#de[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate": {
   "post": {
    "operationId": "gmail.users.settings.cse.keypairs.obliterate",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.obliterate",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
    "tags": [
     "Gmail API"
    ],
    "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages. For administrators managing identities and keypairs for users in their[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable": {
   "post": {
    "operationId": "gmail.users.settings.cse.keypairs.disable",
    "x-executor-toolPath": "gmail.users.settings.cse.keypairs.disable",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
    "tags": [
     "Gmail API"
    ],
    "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://de[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}": {
   "delete": {
    "operationId": "gmail.users.settings.cse.identities.delete",
    "x-executor-toolPath": "gmail.users.settings.cse.identities.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
    "tags": [
     "Gmail API"
    ],
    "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceA[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "get": {
    "operationId": "gmail.users.settings.cse.identities.get",
    "x-executor-toolPath": "gmail.users.settings.cse.identities.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
    "tags": [
     "Gmail API"
    ],
    "description": "Retrieves a client-side encryption identity configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gmail.setti[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/identities": {
   "get": {
    "operationId": "gmail.users.settings.cse.identities.list",
    "x-executor-toolPath": "gmail.users.settings.cse.identities.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/identities",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the client-side encrypted identities for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "post": {
    "operationId": "gmail.users.settings.cse.identities.create",
    "x-executor-toolPath": "gmail.users.settings.cse.identities.create",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/identities",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2Se[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}": {
   "patch": {
    "operationId": "gmail.users.settings.cse.identities.patch",
    "x-executor-toolPath": "gmail.users.settings.cse.identities.patch",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
    "tags": [
     "Gmail API"
    ],
    "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887). For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://develo[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/filters": {
   "get": {
    "operationId": "gmail.users.settings.filters.list",
    "x-executor-toolPath": "gmail.users.settings.filters.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/filters",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the message filters of a Gmail user. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "post": {
    "operationId": "gmail.users.settings.filters.create",
    "x-executor-toolPath": "gmail.users.settings.filters.create",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/filters",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/settings/filters/{id}": {
   "get": {
    "operationId": "gmail.users.settings.filters.get",
    "x-executor-toolPath": "gmail.users.settings.filters.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/filters/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets a filter. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/",
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   },
   "delete": {
    "operationId": "gmail.users.settings.filters.delete",
    "x-executor-toolPath": "gmail.users.settings.filters.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/settings/filters/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Immediately and permanently deletes the specified filter. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/gmail.settings.basic"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/gmail.settings.basic"
    ]
   }
  },
  "/gmail/v1/users/{userId}/drafts": {
   "get": {
    "operationId": "gmail.users.drafts.list",
    "x-executor-toolPath": "gmail.users.drafts.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the drafts in the user's mailbox. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "post": {
    "operationId": "gmail.users.drafts.create",
    "x-executor-toolPath": "gmail.users.drafts.create",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates a draft with the `DRAFT` label. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/drafts/{id}": {
   "put": {
    "operationId": "gmail.users.drafts.update",
    "x-executor-toolPath": "gmail.users.drafts.update",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Replaces a draft's content. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "delete": {
    "operationId": "gmail.users.drafts.delete",
    "x-executor-toolPath": "gmail.users.drafts.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Immediately and permanently deletes the specified draft. Does not simply trash it. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "get": {
    "operationId": "gmail.users.drafts.get",
    "x-executor-toolPath": "gmail.users.drafts.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified draft. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/drafts/{id}": {
   "put": {
    "operationId": "gmail.users.drafts.updateMedia",
    "x-executor-toolPath": "gmail.users.drafts.updateMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/drafts/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Replaces a draft's content. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts). (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/drafts": {
   "post": {
    "operationId": "gmail.users.drafts.createMedia",
    "x-executor-toolPath": "gmail.users.drafts.createMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/drafts",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates a draft with the `DRAFT` label. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts). (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/drafts/send": {
   "post": {
    "operationId": "gmail.users.drafts.send",
    "x-executor-toolPath": "gmail.users.drafts.send",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/drafts/send",
    "tags": [
     "Gmail API"
    ],
    "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/drafts/send": {
   "post": {
    "operationId": "gmail.users.drafts.sendMedia",
    "x-executor-toolPath": "gmail.users.drafts.sendMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/drafts/send",
    "tags": [
     "Gmail API"
    ],
    "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts). (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/threads": {
   "get": {
    "operationId": "gmail.users.threads.list",
    "x-executor-toolPath": "gmail.users.threads.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the threads in the user's mailbox. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/threads/{id}/modify": {
   "post": {
    "operationId": "gmail.users.threads.modify",
    "x-executor-toolPath": "gmail.users.threads.modify",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads/{id}/modify",
    "tags": [
     "Gmail API"
    ],
    "description": "Modifies the labels applied to the thread. This applies to all messages in the thread. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/threads/{id}": {
   "delete": {
    "operationId": "gmail.users.threads.delete",
    "x-executor-toolPath": "gmail.users.threads.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "get": {
    "operationId": "gmail.users.threads.get",
    "x-executor-toolPath": "gmail.users.threads.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified thread. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/threads/{id}/trash": {
   "post": {
    "operationId": "gmail.users.threads.trash",
    "x-executor-toolPath": "gmail.users.threads.trash",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads/{id}/trash",
    "tags": [
     "Gmail API"
    ],
    "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/threads/{id}/untrash": {
   "post": {
    "operationId": "gmail.users.threads.untrash",
    "x-executor-toolPath": "gmail.users.threads.untrash",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/threads/{id}/untrash",
    "tags": [
     "Gmail API"
    ],
    "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/{id}": {
   "get": {
    "operationId": "gmail.users.messages.get",
    "x-executor-toolPath": "gmail.users.messages.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified message.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "delete": {
    "operationId": "gmail.users.messages.delete",
    "x-executor-toolPath": "gmail.users.messages.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/{id}/untrash": {
   "post": {
    "operationId": "gmail.users.messages.untrash",
    "x-executor-toolPath": "gmail.users.messages.untrash",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{id}/untrash",
    "tags": [
     "Gmail API"
    ],
    "description": "Removes the specified message from the trash.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/{id}/trash": {
   "post": {
    "operationId": "gmail.users.messages.trash",
    "x-executor-toolPath": "gmail.users.messages.trash",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{id}/trash",
    "tags": [
     "Gmail API"
    ],
    "description": "Moves the specified message to the trash.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages": {
   "post": {
    "operationId": "gmail.users.messages.insert",
    "x-executor-toolPath": "gmail.users.messages.insert",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages",
    "tags": [
     "Gmail API"
    ],
    "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "get": {
    "operationId": "gmail.users.messages.list",
    "x-executor-toolPath": "gmail.users.messages.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists the messages in the user's mailbox. For more information, see [List Gmail messages](https://developers.google.com/workspace/gmail/api/guides/list-messages).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/messages": {
   "post": {
    "operationId": "gmail.users.messages.insertMedia",
    "x-executor-toolPath": "gmail.users.messages.insertMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/messages",
    "tags": [
     "Gmail API"
    ],
    "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending). (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/batchModify": {
   "post": {
    "operationId": "gmail.users.messages.batchModify",
    "x-executor-toolPath": "gmail.users.messages.batchModify",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/batchModify",
    "tags": [
     "Gmail API"
    ],
    "description": "Modifies the labels and the Classification Label values on the specified messages. For administrators modifying messages for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/g[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/import": {
   "post": {
    "operationId": "gmail.users.messages.import",
    "x-executor-toolPath": "gmail.users.messages.import",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/import",
    "tags": [
     "Gmail API"
    ],
    "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150 MB.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/messages/import": {
   "post": {
    "operationId": "gmail.users.messages.importMedia",
    "x-executor-toolPath": "gmail.users.messages.importMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/messages/import",
    "tags": [
     "Gmail API"
    ],
    "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150 MB. (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/batchDelete": {
   "post": {
    "operationId": "gmail.users.messages.batchDelete",
    "x-executor-toolPath": "gmail.users.messages.batchDelete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/batchDelete",
    "tags": [
     "Gmail API"
    ],
    "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/{id}/modify": {
   "post": {
    "operationId": "gmail.users.messages.modify",
    "x-executor-toolPath": "gmail.users.messages.modify",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{id}/modify",
    "tags": [
     "Gmail API"
    ],
    "description": "Modifies the labels and the Classification Label values on the specified message. For administrators modifying message for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/auth/gma[...]",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/send": {
   "post": {
    "operationId": "gmail.users.messages.send",
    "x-executor-toolPath": "gmail.users.messages.send",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/send",
    "tags": [
     "Gmail API"
    ],
    "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/upload/gmail/v1/users/{userId}/messages/send": {
   "post": {
    "operationId": "gmail.users.messages.sendMedia",
    "x-executor-toolPath": "gmail.users.messages.sendMedia",
    "x-executor-pathTemplate": "/upload/gmail/v1/users/{userId}/messages/send",
    "tags": [
     "Gmail API"
    ],
    "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending). (media upload)",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}": {
   "get": {
    "operationId": "gmail.users.messages.attachments.get",
    "x-executor-toolPath": "gmail.users.messages.attachments.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified message attachment.",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/labels": {
   "get": {
    "operationId": "gmail.users.labels.list",
    "x-executor-toolPath": "gmail.users.labels.list",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels",
    "tags": [
     "Gmail API"
    ],
    "description": "Lists all labels in the user's mailbox. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "post": {
    "operationId": "gmail.users.labels.create",
    "x-executor-toolPath": "gmail.users.labels.create",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels",
    "tags": [
     "Gmail API"
    ],
    "description": "Creates a label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  },
  "/gmail/v1/users/{userId}/labels/{id}": {
   "put": {
    "operationId": "gmail.users.labels.update",
    "x-executor-toolPath": "gmail.users.labels.update",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Updates the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "delete": {
    "operationId": "gmail.users.labels.delete",
    "x-executor-toolPath": "gmail.users.labels.delete",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it's applied to. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "get": {
    "operationId": "gmail.users.labels.get",
    "x-executor-toolPath": "gmail.users.labels.get",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Gets the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   },
   "patch": {
    "operationId": "gmail.users.labels.patch",
    "x-executor-toolPath": "gmail.users.labels.patch",
    "x-executor-pathTemplate": "/gmail/v1/users/{userId}/labels/{id}",
    "tags": [
     "Gmail API"
    ],
    "description": "Patch the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
    "servers": [
     {
      "url": "https://gmail.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://mail.google.com/"
      ]
     }
    ],
    "x-google-scopes": [
     "https://mail.google.com/"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "googleOAuth2": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
       "openid": "",
       "email": "",
       "profile": "",
       "https://mail.google.com/": "",
       "https://www.googleapis.com/auth/gmail.settings.basic": ""
      }
     }
    }
   }
  }
 },
 "security": [
  {
   "googleOAuth2": [
    "openid",
    "email",
    "profile",
    "https://mail.google.com/",
    "https://www.googleapis.com/auth/gmail.settings.basic"
   ]
  }
 ],
 "x-executor-origin": {
  "kind": "googleDiscoveryBundle",
  "services": [
   {
    "discoveryUrl": "https://www.googleapis.com/discovery/v1/apis/gmail/v1/rest",
    "service": "gmail",
    "version": "v1"
   }
  ]
 }
}