{
 "openapi": "3.1.0",
 "info": {
  "title": "Photos Library API",
  "version": "v1",
  "description": "Manage photos, videos, and albums created by your app in Google Photos "
 },
 "servers": [
  {
   "url": "https://www.googleapis.com/"
  }
 ],
 "paths": {
  "/v1/mediaItems:batchCreate": {
   "post": {
    "operationId": "photoslibrary.mediaItems.batchCreate",
    "x-executor-toolPath": "photoslibrary.mediaItems.batchCreate",
    "x-executor-pathTemplate": "/v1/mediaItems:batchCreate",
    "tags": [
     "Photos Library API"
    ],
    "description": "Creates one or more media items in a user's Google Photos library. This is the second step for creating a media item. For details regarding Step 1, uploading the raw bytes to a Google Server, see Uploading media. This call adds the media item to the library. If an app created album `id` is specified, the call adds the media item to the album too. Each album can contain up to 20,000 media items. By default, the media item will be added to the end of the library or album. If an[...]",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.appendonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.appendonly"
    ]
   }
  },
  "/v1/mediaItems:search": {
   "post": {
    "operationId": "photoslibrary.mediaItems.search",
    "x-executor-toolPath": "photoslibrary.mediaItems.search",
    "x-executor-pathTemplate": "/v1/mediaItems:search",
    "tags": [
     "Photos Library API"
    ],
    "description": "Searches for app created media items in a user's Google Photos library. Only media items and ablums created by your app are returned. If no filters are set, then all app created media items in the user's library are returned. If an app created album is set, all media items in the specified album are returned. If filters are specified, app created media items that match the filters from the user's library are listed. If you set both the album and the filters, the request resul[...]",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   }
  },
  "/v1/mediaItems/{mediaItemId}": {
   "get": {
    "operationId": "photoslibrary.mediaItems.get",
    "x-executor-toolPath": "photoslibrary.mediaItems.get",
    "x-executor-pathTemplate": "/v1/mediaItems/{+mediaItemId}",
    "tags": [
     "Photos Library API"
    ],
    "description": "Returns the app created media item for the specified media item identifier.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   }
  },
  "/v1/mediaItems": {
   "get": {
    "operationId": "photoslibrary.mediaItems.list",
    "x-executor-toolPath": "photoslibrary.mediaItems.list",
    "x-executor-pathTemplate": "/v1/mediaItems",
    "tags": [
     "Photos Library API"
    ],
    "description": "List all media items created by your app from a user's Google Photos library.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   }
  },
  "/v1/mediaItems/{id}": {
   "patch": {
    "operationId": "photoslibrary.mediaItems.patch",
    "x-executor-toolPath": "photoslibrary.mediaItems.patch",
    "x-executor-pathTemplate": "/v1/mediaItems/{+id}",
    "tags": [
     "Photos Library API"
    ],
    "description": "Update the app created media item with the specified `id`. Only the `id` and `description` fields of the media item are read. The media item must have been created by the developer via the API.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
    ]
   }
  },
  "/v1/mediaItems:batchGet": {
   "get": {
    "operationId": "photoslibrary.mediaItems.batchGet",
    "x-executor-toolPath": "photoslibrary.mediaItems.batchGet",
    "x-executor-pathTemplate": "/v1/mediaItems:batchGet",
    "tags": [
     "Photos Library API"
    ],
    "description": "Returns the list of app created media items for the specified media item identifiers. Items are returned in the same order as the supplied identifiers.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   }
  },
  "/v1/albums/{id}": {
   "patch": {
    "operationId": "photoslibrary.albums.patch",
    "x-executor-toolPath": "photoslibrary.albums.patch",
    "x-executor-pathTemplate": "/v1/albums/{+id}",
    "tags": [
     "Photos Library API"
    ],
    "description": "Update the app created album with the specified `id`. Only the `id`, `title` and `cover_photo_media_item_id` fields of the album are read. The album must have been created by the developer via the API.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
    ]
   }
  },
  "/v1/albums/{albumId}:batchAddMediaItems": {
   "post": {
    "operationId": "photoslibrary.albums.batchAddMediaItems",
    "x-executor-toolPath": "photoslibrary.albums.batchAddMediaItems",
    "x-executor-pathTemplate": "/v1/albums/{+albumId}:batchAddMediaItems",
    "tags": [
     "Photos Library API"
    ],
    "description": "Adds one or more app created media items in a user's Google Photos library to an app created album. The media items and albums must have been created by the developer via the API. Media items are added to the end of the album. If multiple media items are given, they are added in the order specified in this call. Each album can contain up to 20,000 media items. Partial success is not supported. The entire request will fail if an invalid media item or album is specified.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.appendonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.appendonly",
     "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
    ]
   }
  },
  "/v1/albums/{albumId}:addEnrichment": {
   "post": {
    "operationId": "photoslibrary.albums.addEnrichment",
    "x-executor-toolPath": "photoslibrary.albums.addEnrichment",
    "x-executor-pathTemplate": "/v1/albums/{+albumId}:addEnrichment",
    "tags": [
     "Photos Library API"
    ],
    "description": "Adds an enrichment at a specified position in an app created created album.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.appendonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.appendonly",
     "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
    ]
   }
  },
  "/v1/albums": {
   "get": {
    "operationId": "photoslibrary.albums.list",
    "x-executor-toolPath": "photoslibrary.albums.list",
    "x-executor-pathTemplate": "/v1/albums",
    "tags": [
     "Photos Library API"
    ],
    "description": "Lists all albums created by your app.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   },
   "post": {
    "operationId": "photoslibrary.albums.create",
    "x-executor-toolPath": "photoslibrary.albums.create",
    "x-executor-pathTemplate": "/v1/albums",
    "tags": [
     "Photos Library API"
    ],
    "description": "Creates an album in a user's Google Photos library.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.appendonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.appendonly"
    ]
   }
  },
  "/v1/albums/{albumId}:batchRemoveMediaItems": {
   "post": {
    "operationId": "photoslibrary.albums.batchRemoveMediaItems",
    "x-executor-toolPath": "photoslibrary.albums.batchRemoveMediaItems",
    "x-executor-pathTemplate": "/v1/albums/{+albumId}:batchRemoveMediaItems",
    "tags": [
     "Photos Library API"
    ],
    "description": "Removes one or more app created media items from a specified app created album. The media items and the album must have been created by the developer via the API. Partial success is not supported. The entire request will fail and no action will be performed on the album if an invalid media item or album is specified.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata"
    ]
   }
  },
  "/v1/albums/{albumId}": {
   "get": {
    "operationId": "photoslibrary.albums.get",
    "x-executor-toolPath": "photoslibrary.albums.get",
    "x-executor-pathTemplate": "/v1/albums/{+albumId}",
    "tags": [
     "Photos Library API"
    ],
    "description": "Returns the app created album based on the specified `albumId`. The `albumId` must be the ID of an album created by your app.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
    ]
   }
  },
  "/v1/uploads": {
   "post": {
    "operationId": "photoslibrary.mediaItems.upload",
    "x-executor-toolPath": "photoslibrary.mediaItems.upload",
    "x-executor-pathTemplate": "/v1/uploads",
    "tags": [
     "Photos Library API"
    ],
    "description": "Uploads raw photo or video bytes to Google Photos and returns a plain-text upload token. Call mediaItems.batchCreate with the returned token to create the media item.",
    "servers": [
     {
      "url": "https://photoslibrary.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/photoslibrary.appendonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/photoslibrary.appendonly"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "googleOAuth2": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
       "openid": "",
       "email": "",
       "profile": "",
       "https://www.googleapis.com/auth/photoslibrary.appendonly": "",
       "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata": "",
       "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata": ""
      }
     }
    }
   }
  }
 },
 "security": [
  {
   "googleOAuth2": [
    "openid",
    "email",
    "profile",
    "https://www.googleapis.com/auth/photoslibrary.appendonly",
    "https://www.googleapis.com/auth/photoslibrary.edit.appcreateddata",
    "https://www.googleapis.com/auth/photoslibrary.readonly.appcreateddata"
   ]
  }
 ],
 "x-executor-origin": {
  "kind": "googleDiscoveryBundle",
  "services": [
   {
    "discoveryUrl": "https://www.googleapis.com/discovery/v1/apis/photoslibrary/v1/rest",
    "service": "photoslibrary",
    "version": "v1"
   }
  ]
 }
}