{
 "openapi": "3.1.0",
 "info": {
  "title": "Google Meet API",
  "version": "v2",
  "description": "Create and manage meetings in Google Meet."
 },
 "servers": [
  {
   "url": "https://www.googleapis.com/"
  }
 ],
 "paths": {
  "/v2/{name}": {
   "get": {
    "operationId": "meet.conferenceRecords.get",
    "x-executor-toolPath": "meet.conferenceRecords.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a conference record by conference ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   },
   "patch": {
    "operationId": "meet.spaces.patch",
    "x-executor-toolPath": "meet.spaces.patch",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Updates details about a meeting space. For an example, see [Update a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#update-meeting-space).",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.settings"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.settings"
    ]
   }
  },
  "/v2/conferenceRecords": {
   "get": {
    "operationId": "meet.conferenceRecords.list",
    "x-executor-toolPath": "meet.conferenceRecords.list",
    "x-executor-pathTemplate": "/v2/conferenceRecords",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the conference records. By default, ordered by start time and in descending order.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/smartNotes": {
   "get": {
    "operationId": "meet.conferenceRecords.smartNotes.list",
    "x-executor-toolPath": "meet.conferenceRecords.smartNotes.list",
    "x-executor-pathTemplate": "/v2/{+parent}/smartNotes",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the set of smart notes from the conference record. By default, ordered by start time and in ascending order.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.smartNotes.get": {
   "get": {
    "operationId": "meet.conferenceRecords.smartNotes.get",
    "x-executor-toolPath": "meet.conferenceRecords.smartNotes.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets smart notes by smart note ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.participants.get": {
   "get": {
    "operationId": "meet.conferenceRecords.participants.get",
    "x-executor-toolPath": "meet.conferenceRecords.participants.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a participant by participant ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/participants": {
   "get": {
    "operationId": "meet.conferenceRecords.participants.list",
    "x-executor-toolPath": "meet.conferenceRecords.participants.list",
    "x-executor-pathTemplate": "/v2/{+parent}/participants",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the participants in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted, this API defaults to `'participants/*, next_page_token'`.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.participants.participantSessions.get": {
   "get": {
    "operationId": "meet.conferenceRecords.participants.participantSessions.get",
    "x-executor-toolPath": "meet.conferenceRecords.participants.participantSessions.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a participant session by participant session ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/participantSessions": {
   "get": {
    "operationId": "meet.conferenceRecords.participants.participantSessions.list",
    "x-executor-toolPath": "meet.conferenceRecords.participants.participantSessions.list",
    "x-executor-pathTemplate": "/v2/{+parent}/participantSessions",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the participant sessions of a participant in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted this API defaults to `'participantsessions/*, next_page_token'`.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.transcripts.get": {
   "get": {
    "operationId": "meet.conferenceRecords.transcripts.get",
    "x-executor-toolPath": "meet.conferenceRecords.transcripts.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a transcript by transcript ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/transcripts": {
   "get": {
    "operationId": "meet.conferenceRecords.transcripts.list",
    "x-executor-toolPath": "meet.conferenceRecords.transcripts.list",
    "x-executor-pathTemplate": "/v2/{+parent}/transcripts",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the set of transcripts from the conference record. By default, ordered by start time and in ascending order.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.transcripts.entries.get": {
   "get": {
    "operationId": "meet.conferenceRecords.transcripts.entries.get",
    "x-executor-toolPath": "meet.conferenceRecords.transcripts.entries.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a `TranscriptEntry` resource by entry ID. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when 1) we have interleaved speakers within milliseconds, or 2) the Google Docs transcript file is modified after generation.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/entries": {
   "get": {
    "operationId": "meet.conferenceRecords.transcripts.entries.list",
    "x-executor-toolPath": "meet.conferenceRecords.transcripts.entries.list",
    "x-executor-pathTemplate": "/v2/{+parent}/entries",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the structured transcript entries per transcript. By default, ordered by start time and in ascending order. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when 1) we have interleaved speakers within milliseconds, or 2) the Google Docs transcript file is modified after generation.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{parent}/recordings": {
   "get": {
    "operationId": "meet.conferenceRecords.recordings.list",
    "x-executor-toolPath": "meet.conferenceRecords.recordings.list",
    "x-executor-pathTemplate": "/v2/{+parent}/recordings",
    "tags": [
     "Google Meet API"
    ],
    "description": "Lists the recording resources from the conference record. By default, ordered by start time and in ascending order.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/meet.conferenceRecords.recordings.get": {
   "get": {
    "operationId": "meet.conferenceRecords.recordings.get",
    "x-executor-toolPath": "meet.conferenceRecords.recordings.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets a recording by recording ID.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly"
    ]
   }
  },
  "/v2/{name}:endActiveConference": {
   "post": {
    "operationId": "meet.spaces.endActiveConference",
    "x-executor-toolPath": "meet.spaces.endActiveConference",
    "x-executor-pathTemplate": "/v2/{+name}:endActiveConference",
    "tags": [
     "Google Meet API"
    ],
    "description": "Ends an active conference (if there's one). For an example, see [End active conference](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#end-active-conference).",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created"
    ]
   }
  },
  "/v2/spaces": {
   "post": {
    "operationId": "meet.spaces.create",
    "x-executor-toolPath": "meet.spaces.create",
    "x-executor-pathTemplate": "/v2/spaces",
    "tags": [
     "Google Meet API"
    ],
    "description": "Creates a space.",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created"
    ]
   }
  },
  "/meet.spaces.get": {
   "get": {
    "operationId": "meet.spaces.get",
    "x-executor-toolPath": "meet.spaces.get",
    "x-executor-pathTemplate": "/v2/{+name}",
    "tags": [
     "Google Meet API"
    ],
    "description": "Gets details about a meeting space. For an example, see [Get a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#get-meeting-space).",
    "servers": [
     {
      "url": "https://meet.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.created"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.readonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/meetings.space.settings"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/meetings.space.created",
     "https://www.googleapis.com/auth/meetings.space.readonly",
     "https://www.googleapis.com/auth/meetings.space.settings"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "googleOAuth2": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
       "openid": "",
       "email": "",
       "profile": "",
       "https://www.googleapis.com/auth/meetings.space.created": "",
       "https://www.googleapis.com/auth/meetings.space.readonly": "",
       "https://www.googleapis.com/auth/meetings.space.settings": ""
      }
     }
    }
   }
  }
 },
 "security": [
  {
   "googleOAuth2": [
    "openid",
    "email",
    "profile",
    "https://www.googleapis.com/auth/meetings.space.created",
    "https://www.googleapis.com/auth/meetings.space.readonly",
    "https://www.googleapis.com/auth/meetings.space.settings"
   ]
  }
 ],
 "x-executor-origin": {
  "kind": "googleDiscoveryBundle",
  "services": [
   {
    "discoveryUrl": "https://www.googleapis.com/discovery/v1/apis/meet/v2/rest",
    "service": "meet",
    "version": "v2"
   }
  ]
 }
}