{
 "openapi": "3.1.0",
 "info": {
  "title": "People API",
  "version": "v1",
  "description": "Provides access to information about profiles and contacts."
 },
 "servers": [
  {
   "url": "https://www.googleapis.com/"
  }
 ],
 "paths": {
  "/v1/{resourceName}:updateContactPhoto": {
   "patch": {
    "operationId": "people.people.updateContactPhoto",
    "x-executor-toolPath": "people.people.updateContactPhoto",
    "x-executor-pathTemplate": "/v1/{+resourceName}:updateContactPhoto",
    "tags": [
     "People API"
    ],
    "description": "Update a contact's photo. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/{resourceName}": {
   "get": {
    "operationId": "people.people.get",
    "x-executor-toolPath": "people.people.get",
    "x-executor-pathTemplate": "/v1/{+resourceName}",
    "tags": [
     "People API"
    ],
    "description": "Provides information about a person by specifying a resource name. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "openid"
      ]
     },
     {
      "googleOAuth2": [
       "email"
      ]
     },
     {
      "googleOAuth2": [
       "profile"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts.other.readonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/directory.readonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.addresses.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.birthday.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.emails.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.gender.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.organization.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.phonenumbers.read"
      ]
     }
    ],
    "x-google-scopes": [
     "openid",
     "email",
     "profile",
     "https://www.googleapis.com/auth/contacts",
     "https://www.googleapis.com/auth/contacts.other.readonly",
     "https://www.googleapis.com/auth/directory.readonly",
     "https://www.googleapis.com/auth/user.addresses.read",
     "https://www.googleapis.com/auth/user.birthday.read",
     "https://www.googleapis.com/auth/user.emails.read",
     "https://www.googleapis.com/auth/user.gender.read",
     "https://www.googleapis.com/auth/user.organization.read",
     "https://www.googleapis.com/auth/user.phonenumbers.read"
    ]
   },
   "put": {
    "operationId": "people.contactGroups.update",
    "x-executor-toolPath": "people.contactGroups.update",
    "x-executor-pathTemplate": "/v1/{+resourceName}",
    "tags": [
     "People API"
    ],
    "description": "Update the name of an existing contact group owned by the authenticated user. Updated contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   },
   "delete": {
    "operationId": "people.contactGroups.delete",
    "x-executor-toolPath": "people.contactGroups.delete",
    "x-executor-pathTemplate": "/v1/{+resourceName}",
    "tags": [
     "People API"
    ],
    "description": "Delete an existing contact group owned by the authenticated user by specifying a contact group resource name. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:batchCreateContacts": {
   "post": {
    "operationId": "people.people.batchCreateContacts",
    "x-executor-toolPath": "people.people.batchCreateContacts",
    "x-executor-pathTemplate": "/v1/people:batchCreateContacts",
    "tags": [
     "People API"
    ],
    "description": "Create a batch of new contacts and return the PersonResponses for the newly Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/{resourceName}:deleteContact": {
   "delete": {
    "operationId": "people.people.deleteContact",
    "x-executor-toolPath": "people.people.deleteContact",
    "x-executor-pathTemplate": "/v1/{+resourceName}:deleteContact",
    "tags": [
     "People API"
    ],
    "description": "Delete a contact person. Any non-contact data will not be deleted. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/{resourceName}:deleteContactPhoto": {
   "delete": {
    "operationId": "people.people.deleteContactPhoto",
    "x-executor-toolPath": "people.people.deleteContactPhoto",
    "x-executor-pathTemplate": "/v1/{+resourceName}:deleteContactPhoto",
    "tags": [
     "People API"
    ],
    "description": "Delete a contact's photo. Mutate requests for the same user should be done sequentially to avoid // lock contention.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:listDirectoryPeople": {
   "get": {
    "operationId": "people.people.listDirectoryPeople",
    "x-executor-toolPath": "people.people.listDirectoryPeople",
    "x-executor-pathTemplate": "/v1/people:listDirectoryPeople",
    "tags": [
     "People API"
    ],
    "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory. When the `sync_token` is specified, resources deleted since the last sync will be returned as a person with `PersonMetadata.deleted` set to true. When the `page_token` or `sync_token` is specified, all other request parameters must match the first call. Writes may have a propagation delay of several minutes for sync requests. Incremental syncs are not intended for read-after-w[...]",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/directory.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/directory.readonly"
    ]
   }
  },
  "/v1/{resourceName}:updateContact": {
   "patch": {
    "operationId": "people.people.updateContact",
    "x-executor-toolPath": "people.people.updateContact",
    "x-executor-pathTemplate": "/v1/{+resourceName}:updateContact",
    "tags": [
     "People API"
    ],
    "description": "Update contact data for an existing contact person. Any non-contact data will not be modified. Any non-contact data in the person to update will be ignored. All fields specified in the `update_mask` will be replaced. The server returns a 400 error if `person.metadata.sources` is not specified for the contact to be updated or if there is no contact source. The server returns a 400 error with reason `\"failedPrecondition\"` if `person.metadata.sources.etag` is different than th[...]",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:batchUpdateContacts": {
   "post": {
    "operationId": "people.people.batchUpdateContacts",
    "x-executor-toolPath": "people.people.batchUpdateContacts",
    "x-executor-pathTemplate": "/v1/people:batchUpdateContacts",
    "tags": [
     "People API"
    ],
    "description": "Update a batch of contacts and return a map of resource names to PersonResponses for the updated contacts. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:searchContacts": {
   "get": {
    "operationId": "people.people.searchContacts",
    "x-executor-toolPath": "people.people.searchContacts",
    "x-executor-pathTemplate": "/v1/people:searchContacts",
    "tags": [
     "People API"
    ],
    "description": "Provides a list of contacts in the authenticated user's grouped contacts that matches the search query. The query matches on a contact's `names`, `nickNames`, `emailAddresses`, `phoneNumbers`, and `organizations` fields that are from the CONTACT source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/contacts#search_the_users_contacts",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:createContact": {
   "post": {
    "operationId": "people.people.createContact",
    "x-executor-toolPath": "people.people.createContact",
    "x-executor-pathTemplate": "/v1/people:createContact",
    "tags": [
     "People API"
    ],
    "description": "Create a new contact and return the person resource for that contact. The request returns a 400 error if more than one field is specified on a field that is a singleton for contact sources: * biographies * birthdays * genders * names Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:batchGet": {
   "get": {
    "operationId": "people.people.getBatchGet",
    "x-executor-toolPath": "people.people.getBatchGet",
    "x-executor-pathTemplate": "/v1/people:batchGet",
    "tags": [
     "People API"
    ],
    "description": "Provides information about a list of specific people by specifying a list of requested resource names. Use `people/me` to indicate the authenticated user. The request returns a 400 error if 'personFields' is not specified.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "openid"
      ]
     },
     {
      "googleOAuth2": [
       "email"
      ]
     },
     {
      "googleOAuth2": [
       "profile"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts.other.readonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/directory.readonly"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.addresses.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.birthday.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.emails.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.gender.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.organization.read"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/user.phonenumbers.read"
      ]
     }
    ],
    "x-google-scopes": [
     "openid",
     "email",
     "profile",
     "https://www.googleapis.com/auth/contacts",
     "https://www.googleapis.com/auth/contacts.other.readonly",
     "https://www.googleapis.com/auth/directory.readonly",
     "https://www.googleapis.com/auth/user.addresses.read",
     "https://www.googleapis.com/auth/user.birthday.read",
     "https://www.googleapis.com/auth/user.emails.read",
     "https://www.googleapis.com/auth/user.gender.read",
     "https://www.googleapis.com/auth/user.organization.read",
     "https://www.googleapis.com/auth/user.phonenumbers.read"
    ]
   }
  },
  "/v1/people:batchDeleteContacts": {
   "post": {
    "operationId": "people.people.batchDeleteContacts",
    "x-executor-toolPath": "people.people.batchDeleteContacts",
    "x-executor-pathTemplate": "/v1/people:batchDeleteContacts",
    "tags": [
     "People API"
    ],
    "description": "Delete a batch of contacts. Any non-contact data will not be deleted. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/people:searchDirectoryPeople": {
   "get": {
    "operationId": "people.people.searchDirectoryPeople",
    "x-executor-toolPath": "people.people.searchDirectoryPeople",
    "x-executor-pathTemplate": "/v1/people:searchDirectoryPeople",
    "tags": [
     "People API"
    ],
    "description": "Provides a list of domain profiles and domain contacts in the authenticated user's domain directory that match the search query.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/directory.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/directory.readonly"
    ]
   }
  },
  "/v1/{resourceName}/connections": {
   "get": {
    "operationId": "people.people.connections.list",
    "x-executor-toolPath": "people.people.connections.list",
    "x-executor-pathTemplate": "/v1/{+resourceName}/connections",
    "tags": [
     "People API"
    ],
    "description": "Provides a list of the authenticated user's contacts. Sync tokens expire 7 days after the full sync. A request with an expired sync token will get an error with an [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info) with reason \"EXPIRED_SYNC_TOKEN\". In the case of such an error clients should make a full sync request without a `sync_token`. The first page of a full sync request has an additional quota. If the quota is exceeded, a 429 error will be[...]",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/{resourceName}:copyOtherContactToMyContactsGroup": {
   "post": {
    "operationId": "people.otherContacts.copyOtherContactToMyContactsGroup",
    "x-executor-toolPath": "people.otherContacts.copyOtherContactToMyContactsGroup",
    "x-executor-pathTemplate": "/v1/{+resourceName}:copyOtherContactToMyContactsGroup",
    "tags": [
     "People API"
    ],
    "description": "Copies an \"Other contact\" to a new contact in the user's \"myContacts\" group Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     },
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts.other.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts",
     "https://www.googleapis.com/auth/contacts.other.readonly"
    ]
   }
  },
  "/v1/otherContacts:search": {
   "get": {
    "operationId": "people.otherContacts.search",
    "x-executor-toolPath": "people.otherContacts.search",
    "x-executor-pathTemplate": "/v1/otherContacts:search",
    "tags": [
     "People API"
    ],
    "description": "Provides a list of contacts in the authenticated user's other contacts that matches the search query. The query matches on a contact's `names`, `emailAddresses`, and `phoneNumbers` fields that are from the OTHER_CONTACT source. **IMPORTANT**: Before searching, clients should send a warmup request with an empty query to update the cache. See https://developers.google.com/people/v1/other-contacts#search_the_users_other_contacts",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts.other.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts.other.readonly"
    ]
   }
  },
  "/v1/otherContacts": {
   "get": {
    "operationId": "people.otherContacts.list",
    "x-executor-toolPath": "people.otherContacts.list",
    "x-executor-pathTemplate": "/v1/otherContacts",
    "tags": [
     "People API"
    ],
    "description": "List all \"Other contacts\", that is contacts that are not in a contact group. \"Other contacts\" are typically auto created contacts from interactions. Sync tokens expire 7 days after the full sync. A request with an expired sync token will get an error with an [google.rpc.ErrorInfo](https://cloud.google.com/apis/design/errors#error_info) with reason \"EXPIRED_SYNC_TOKEN\". In the case of such an error clients should make a full sync request without a `sync_token`. The first[...]",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts.other.readonly"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts.other.readonly"
    ]
   }
  },
  "/v1/contactGroups": {
   "post": {
    "operationId": "people.contactGroups.create",
    "x-executor-toolPath": "people.contactGroups.create",
    "x-executor-pathTemplate": "/v1/contactGroups",
    "tags": [
     "People API"
    ],
    "description": "Create a new contact group owned by the authenticated user. Created contact group names must be unique to the users contact groups. Attempting to create a group with a duplicate name will return a HTTP 409 error. Mutate requests for the same user should be sent sequentially to avoid increased latency and failures.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   },
   "get": {
    "operationId": "people.contactGroups.list",
    "x-executor-toolPath": "people.contactGroups.list",
    "x-executor-pathTemplate": "/v1/contactGroups",
    "tags": [
     "People API"
    ],
    "description": "List all contact groups owned by the authenticated user. Members of the contact groups are not populated.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/people.contactGroups.get": {
   "get": {
    "operationId": "people.contactGroups.get",
    "x-executor-toolPath": "people.contactGroups.get",
    "x-executor-pathTemplate": "/v1/{+resourceName}",
    "tags": [
     "People API"
    ],
    "description": "Get a specific contact group owned by the authenticated user by specifying a contact group resource name.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/contactGroups:batchGet": {
   "get": {
    "operationId": "people.contactGroups.batchGet",
    "x-executor-toolPath": "people.contactGroups.batchGet",
    "x-executor-pathTemplate": "/v1/contactGroups:batchGet",
    "tags": [
     "People API"
    ],
    "description": "Get a list of contact groups owned by the authenticated user by specifying a list of contact group resource names.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  },
  "/v1/{resourceName}/members:modify": {
   "post": {
    "operationId": "people.contactGroups.members.modify",
    "x-executor-toolPath": "people.contactGroups.members.modify",
    "x-executor-pathTemplate": "/v1/{+resourceName}/members:modify",
    "tags": [
     "People API"
    ],
    "description": "Modify the members of a contact group owned by the authenticated user. The only system contact groups that can have members added are `contactGroups/myContacts` and `contactGroups/starred`. Other system contact groups are deprecated and can only have contacts removed.",
    "servers": [
     {
      "url": "https://people.googleapis.com/"
     }
    ],
    "security": [
     {
      "googleOAuth2": [
       "https://www.googleapis.com/auth/contacts"
      ]
     }
    ],
    "x-google-scopes": [
     "https://www.googleapis.com/auth/contacts"
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "googleOAuth2": {
    "type": "oauth2",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
      "tokenUrl": "https://oauth2.googleapis.com/token",
      "scopes": {
       "openid": "",
       "email": "",
       "profile": "",
       "https://www.googleapis.com/auth/contacts": "",
       "https://www.googleapis.com/auth/contacts.other.readonly": "",
       "https://www.googleapis.com/auth/directory.readonly": "",
       "https://www.googleapis.com/auth/user.addresses.read": "",
       "https://www.googleapis.com/auth/user.birthday.read": "",
       "https://www.googleapis.com/auth/user.emails.read": "",
       "https://www.googleapis.com/auth/user.gender.read": "",
       "https://www.googleapis.com/auth/user.organization.read": "",
       "https://www.googleapis.com/auth/user.phonenumbers.read": ""
      }
     }
    }
   }
  }
 },
 "security": [
  {
   "googleOAuth2": [
    "openid",
    "email",
    "profile",
    "https://www.googleapis.com/auth/contacts",
    "https://www.googleapis.com/auth/contacts.other.readonly",
    "https://www.googleapis.com/auth/directory.readonly",
    "https://www.googleapis.com/auth/user.addresses.read",
    "https://www.googleapis.com/auth/user.birthday.read",
    "https://www.googleapis.com/auth/user.emails.read",
    "https://www.googleapis.com/auth/user.gender.read",
    "https://www.googleapis.com/auth/user.organization.read",
    "https://www.googleapis.com/auth/user.phonenumbers.read"
   ]
  }
 ],
 "x-executor-origin": {
  "kind": "googleDiscoveryBundle",
  "services": [
   {
    "discoveryUrl": "https://www.googleapis.com/discovery/v1/apis/people/v1/rest",
    "service": "people",
    "version": "v1"
   }
  ]
 }
}